export const codeItDataActionTypes = {
    SET_CODES: 'SET_CODES',
    SET_KEYWORDS: 'SET_KEYWORDS',
    INCREASE_PROGRESS_LENGTH:"INCREASE_PROGRESS_LENGTH",
    DECREASE_PROGRESS_LENGTH:"DECREASE_PROGRESS_LENGTH",
    INCREASE_NUMBER_OF_INPUTS:"INCREASE_NUMBER_OF_INPUTS",
    DECREASE_NUMBER_OF_INPUTS:"DECREASE_NUMBER_OF_INPUTS",
    SET_SELECTED_ROWS : 'SET_SELECTED_ROWS',
    SET_FILTERED_DATA : 'SET_FILTERED_DATA',
    SET_QUESTION_NUMBER : 'SET_QUESTION_NUMBER',
    SET_LEFT_MENU_CODES:"SET_LEFT_MENU_CODES",
    SET_SORT_BY:"SET_SORT_BY",
    SET_CODING_SUMMARY:"SET_CODING_SUMMARY",
};
  