export const excelDataActionTypes = {
    SET_EXCEL_DATA: 'SET_EXCEL_DATA',
    SET_EXCEL_DATA_COLUMNS: 'SET_EXCEL_DATA_COLUMNS',
    SET_EXCEL_FILE_NAME:'SET_EXCEL_FILE_NAME',
    SET_EXCEL_DATA_HEADERS: 'SET_EXCEL_DATA_HEADERS',
  };
  