const RESPONSE_MESSAGE ={
  userRegistered: 'User is registered successfully.',
  userExist:'User is already exists.',
  userNotFound:'User not found.',
  passwordNotFound:'Please reset your password.',
  passwordNotMatch:'Please enter a valid password.',
  unverifiedUser:'Please verify your account.',
  verificationEmail:'Verification Email send on register email, please verify your account.',
  resetPasswordEmail:'Reset password send to register email, please reset your password.',
  OTPsent:'OTP is send successfully on register Phone Number.',
  passwordChanged:'Password is change successfully.',
  invalidUser:'Invalid User',
  profileChanged:'Profile is changed successfullysave successfully.',
  internalError: 'Internal Server Error',
  profileImageFormat:'Only .jpg, .jpeg and .png formate is allowed.',
  profileImageUpload: 'Profile Image is uploaded successfully.',
  profileImageDelete: 'Profile Image is removed successfully.',
  docFileFormat: 'Only .xlsx, .xls and .cvs formate is allowed.',
  docFileSave:'doument file is saved successfully.',
  docFileDelete:'doument file is deleted successfully.',
  projectCreated:'Project is created successfully',
}
export default RESPONSE_MESSAGE